### ISSUE TITLE
Campo "Fecha de nacimiento" sin formato establecido

### ISSUE THREAD

**Issue by JohanJimenex** [JohanJimenex/event-webapp-frontend#12]
**Versión y link de la aplicación:**
**v.1.0** Link: https://johanjimenex.github.io/event-webapp-frontend/pages/register.html

**Navegador** (opcional):
Chrome

**Descripción:**
El campo "Fecha de nacimiento" no tiene el tipado correcto que es type="date" para que acepte solo formato de fecha.

**Pasos para reproducir el defecto:**
1. Abrir página web en el navegador preferido.
2. Ingresar a la página de 'Registrarse"
3. Colocar letras en el campo de "Año de nacimiento"

**Resultado esperado:**
Permite solo ingresar formato de fecha, (23/04/1991)

**Resultado obtenido:**
El campo permite ingresar todo tipo de caracteres.

**Evidencia** (capturas):
(Captura adjunta) ![](https://trello.com/1/cards/62daa3770ec93166fcbac935/attachments/62daa52989fb35422208f2d1/download/Monosnap_Hey!_Tickets_2022-07-22_09-24-46.jpg)

**Comment by JohanJimenex** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Campo "Fecha de nacimiento" sin formato establecido](https://trello.com/c/hm1lViKb/51-campo-fecha-de-nacimiento-sin-formato-establecido)

**Comment by JAndresGarcia** [comment]
Se me pasó esa parte, lo soluciono rápido y hago el commit

**Comment by JohanJimenex** [comment]
Tranqui, esto es parte del día a día jejeje ,   
PD:  el tipo  es date  en el atributo type="date"
